version: '3.8'

services:
  app:
    build:
      dockerfile:  ./Dockerfile
      context: .
      target: app
    container_name: wind-curtailment
    ports:
        - 8084:8082
    volumes:
      - ./lib:/src/lib
      - ./data:/src/data

  etl:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: etl
    container_name: wind-curtailment-etl
    ports:
      - "8000:8000"
    volumes:
      - ./lib:/src/lib
      - ./scripts:/src/scripts
      - ./data:/src/data
      - ./:/src/
    env_file:
      - .env
    entrypoint:  uvicorn etl:app --reload --host "0.0.0.0"


