version: '3.8'

services:
  app:
    build:
      dockerfile:  ./Dockerfile
      context: .
    container_name: wind-curtailment
    ports:
        - 8083:8082
    volumes:
      - ./lib:/lib
      - ./data:/data