version: '3.8'

services:
  app:
    build:
      dockerfile:  ./Dockerfile
      context: .
    container_name: wind-curtailment
    ports:
        - 8084:8082
    volumes:
      - ./lib:/src/lib
      - ./data:/src/data