name: Deploy

on:
  push:
    branches: [ add-streamlit-app ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and publish image to GCR
      uses: carbonchain/action-container-registry@v1.1
      with:
        project_id: wind-curtailment
        dockerfile: ./Dockerfile
        image: gcr.io/wind-curtailment/app
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@v1.6
      with:
        image: gcr.io/wind-curtailment/app
        service: wind-curtailment-app
        project: wind-curtailment
        region: europe-north1
        service key: ${{ secrets.GCLOUD_AUTH }}